kino_app/urls.py
"""
This file is part of KinoAi project.
It is subject to the license terms in the LICENSE file found in the top-level directory
"""


from django.urls import path

from . import views
from . import KinoAiIndexViews
from . import VideoEditingViews
from . import VideoBookViews
from . import VideosLibraryViews
from . import CorpusViews
from . import NotingViews

app_name = 'kino_app'
urlpatterns = [
    path('', KinoAiIndexViews.IndexView.as_view(), name='index'),
    path('set_previous', KinoAiIndexViews.set_previous, name='set_previous'),
    path('modify_password', KinoAiIndexViews.modify_password, name='modify_password'),
    path('create_project', KinoAiIndexViews.create_project, name='create_project'),
    path('check_project', KinoAiIndexViews.check_project, name='check_project'),
    path('edit_project', KinoAiIndexViews.edit_project, name='edit_project'),
    path('remove_project', KinoAiIndexViews.remove_project, name='remove_project'),
    path('modified_path', KinoAiIndexViews.modified_path, name='modified_path'),
    path('update_json_shots', KinoAiIndexViews.update_json_shots, name='update_json_shots'),
    path('preprocess', KinoAiIndexViews.preprocess, name='preprocess'),
    path('upload', KinoAiIndexViews.upload_view, name='upload'),

    path('video_book/<int:id>/<str:name_notebook>', VideoBookViews.video_book, name='video_book'),
    path('video_book/save_note_video', VideoBookViews.save_note_video, name='save_note_video'),
    path('video_book/extract_image_full_crop', VideoBookViews.extract_image_full_crop, name='extract_image_full_crop'),
    path('video_book/get_full_data_shots', VideoBookViews.get_full_data_shots, name='get_full_data_shots'),

    path('corpus_search/<project>', CorpusViews.corpus_search, name='corpus_search'),
    path('add_text', CorpusViews.add_text, name='add_text'),
    path('remove_text', CorpusViews.remove_text, name='remove_text'),
    path('add_actor_corpus', CorpusViews.add_actor_corpus, name='add_actor_corpus'),
    path('save_partition_text', CorpusViews.save_partition_text, name='save_partition_text'),

    path('videos_library/<project>', VideosLibraryViews.videos_library_app, name='videos_library_app'),
    path('check_password_library', VideosLibraryViews.check_password_library, name='check_password_library'),
    path('set_library_false', VideosLibraryViews.set_library_false, name='set_library_false'),
    path('upload_video_library', VideosLibraryViews.upload_video_library, name='upload_video_library'),
    path('remove_video_library', VideosLibraryViews.remove_video_library, name='remove_video_library'),

    path('noting_app/<project>', NotingViews.noting_app, name='noting_app'),
    path('download_notes', NotingViews.download_notes, name='download_notes'),
    path('save_notes', NotingViews.save_notes, name='save_notes'),
    path('download_subs', NotingViews.download_subs, name='download_subs'),

    path('video_editing/<int:id>', VideoEditingViews.video_editing, name='video_editing'),
    path('video_editing/get_data_detec', VideoEditingViews.get_data_detec, name='get_data_detec'),
    path('video_editing/get_data_shots', VideoEditingViews.get_data_shots, name='get_data_shots'),
    path('video_editing/save_shot_perso', VideoEditingViews.save_shot_perso, name='save_shot_perso'),
    path('video_editing/submit', VideoEditingViews.submit, name='submit'),
    path('video_editing/remove_shot', VideoEditingViews.remove_shot, name='remove_shot'),
    path('video_editing/save_timeline', VideoEditingViews.save_timeline, name='save_timeline'),
    path('video_editing/save_note', VideoEditingViews.save_note, name='save_note'),
    path('video_editing/save_partitions', VideoEditingViews.save_partitions, name='save_partitions'),
    path('video_editing/upload_rough_cut', VideoEditingViews.upload_rough_cut, name='upload_rough'),
    path('video_editing/load_sub', VideoEditingViews.load_sub, name='load_sub'),
    path('video_editing/load_json', VideoEditingViews.load_json, name='load_json'),
    path('video_editing/download_vtt', VideoEditingViews.download_vtt, name='download_vtt'),
    path('video_editing/stabilize', VideoEditingViews.stabilize, name='stabilize'),
    path('video_editing/stabilize_split_merge', VideoEditingViews.stabilize_split_merge, name='stabilize_split_merge'),
    path('video_editing/split_screen_layout_configuration', VideoEditingViews.split_screen_layout_configuration, name='split_screen_layout_configuration'),
    path('video_editing/save_split_screen_final', VideoEditingViews.save_split_screen_final, name='save_split_screen_final'),
    path('video_editing/remove_split_screen', VideoEditingViews.remove_split_screen, name='remove_split_screen'),
    path('video_editing/fullhd', VideoEditingViews.fullhd, name='fullhd'),
    path('video_editing/processKeyFrames', VideoEditingViews.processKeyFrames, name='processKeyFrames'),
    path('video_editing/check_progress_bar', VideoEditingViews.check_progress_bar, name='check_progress_bar'),
    path('video_editing/delete_video', VideoEditingViews.delete_video, name='delete_video'),
    path('video_editing/reframeMov', VideoEditingViews.reframeMov, name='reframeMov')
]

kinoai/urls.py
"""kino_site URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.urls import include, path
from django.contrib import admin
from kino_app.views import LoginView, logout_view, signup_view, reset_password
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('kino_app/', include('kino_app.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/sign_up/', signup_view, name='sign_up'),
    path('accounts/reset_password/', reset_password, name='reset_password'),
    path('', LoginView.as_view(), name='login'),
    path('accounts/logout/', logout_view, name='logout'),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kino_app/models.py
"""
This file is part of KinoAi project.
It is subject to the license terms in the LICENSE file found in the top-level directory
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class FolderPath(models.Model):
    title = models.TextField(default="")
    path = models.TextField()
    abs_path = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, default=None)

class Detections(models.Model):
    json_data = models.TextField()
    path = models.ForeignKey(FolderPath, models.SET_NULL, blank=True, null=True,)

class Shots(models.Model):
    json_data = models.TextField()
    path = models.ForeignKey(FolderPath, models.SET_NULL, blank=True, null=True,)

class Project(models.Model):
    title = models.TextField()
    company = models.TextField()
    date = models.DateField()
    password = models.TextField(blank=True, null=True, default=None)

kino_app/forms.py
"""
This file is part of KinoAi project.
It is subject to the license terms in the LICENSE file found in the top-level directory
"""


from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

kino_app/views.py
"""
This file is part of KinoAi project.
It is subject to the license terms in the LICENSE file found in the top-level directory
"""

from django.shortcuts import get_object_or_404, render, redirect
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password, check_password, is_password_usable
from django.contrib.auth.models import Permission, User
from django.views.decorators.csrf import csrf_exempt
from .models import FolderPath, Detections, Shots, Project
from django.core.files.storage import FileSystemStorage
from django.views.decorators.cache import never_cache
from django.utils.dateparse import parse_date

from . import utils
import os
import json
import re
import cvxpy as cvx
import numpy as np
import scipy as sp
import scipy.sparse
from . import StabilizeOptimizer as stab
from . import StabilizeOptimizerConstraintStartEnd as stab_cons
from . import StabilizeSplitAndMerge as stab_split_merge
from . import SplitScreenOptimizer as split_opt
from moviepy.editor import VideoFileClip, ImageSequenceClip, AudioFileClip
import subprocess
import shutil
import ctypes
import math, random
import time
import cv2
#  command ffmpeg for extract screeshot at 32.375 sec ffmpeg -ss 32.375 -i original_hevc.mov -frames:v 1 out1.jpg

class LoginView(generic.View):
    template_name='kino_app/login.html'
    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active and user.is_authenticated == True:
                login(request, user)
                return HttpResponseRedirect('/kino_app')
            else:
                return render(request, "kino_app/login.html", {'msg':"Inactive user"}, {'left_part':random.randint(1,10), 'right_part':random.randint(1,20)})
        else:
            return render(request, "kino_app/login.html", {'msg':"Username or password invalid"}, {'left_part':random.randint(1,10), 'right_part':random.randint(1,20)})

        return render(request, "kino_app/login.html", {'left_part':random.randint(1,10), 'right_part':random.randint(1,20)})
    def get(self, request):
        return render(request, "kino_app/login.html", {'left_part':random.randint(1,10), 'right_part':random.randint(1,20)})

def logout_view(request):
    print(request.user)
    logout(request)
    return HttpResponseRedirect(settings.LOGIN_URL)

def signup_view(request):
    if request.method == "POST":
        print(request.POST)
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        left = int(request.POST['left_part'])
        right = int(request.POST['right_part'])
        if request.POST['answer'] != "":
            answer = int(request.POST['answer'])
            if not ((left+answer)==right or (left-answer)==right):
                return render(request, "kino_app/login.html", {'msg':'Check your math !', 'left_part':random.randint(1,10), 'right_part':random.randint(1,20)})
        else:
            return render(request, "kino_app/login.html", {'msg':'Check your math !', 'left_part':random.randint(1,10), 'right_part':random.randint(1,20)})
        if username:
            user_set = User.objects.filter(username=username)
            if len(user_set) == 0:
                user = User.objects.create_user(username=username, email=email, password=password)
                print(user)
                return HttpResponseRedirect(settings.LOGIN_URL)
            else :
                return render(request, "kino_app/login.html", {'msg':'Username already used', 'left_part':random.randint(1,10), 'right_part':random.randint(1,20)})

    return render(request, "kino_app/login.html", {'left_part':random.randint(1,10), 'right_part':random.randint(1,20)})

def reset_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        u = User.objects.get(username__exact=username)

        if u.email == email:
            password = User.objects.make_random_password()
            u.email_user('Reset your password','New password '+password)
            u.set_password(password)
            u.save()
            print('Le nouveau '+password)
            return render(request, "kino_app/reset_password.html", {'msg':'Visit your mailbox to reset your password', 'reset':True})
        else:
            return render(request, "kino_app/reset_password.html", {'msg':'Wrong email or username'})
    return render(request, "kino_app/reset_password.html")

kino_app/templates/kino_app/process.html
<!--
This file is part of KinoAi project.
It is subject to the license terms in the LICENSE file found in the top-level directory
-->

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'kino_app/kino_ai/stylesheets/sign_up.css' %}">
<title> Kino AI </title>

<div id="img_logo">
  <a href="{% url 'kino_app:index' %}" > <img id="logo" width="480" height="300" src="{% static 'kino_app/logo/logo_cut.png' %}" ></a>

</div>

{% if uploaded_file_url %}
  <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
{% endif %}

kino_app/templates/kino_app/upload.html
<!--
This file is part of KinoAi project.
It is subject to the license terms in the LICENSE file found in the top-level directory
-->

{% load static %}
{% load string_filter %}
<link rel="stylesheet" type="text/css" href="{% static 'kino_app/kino_ai/stylesheets/sign_up.css' %}">
<title> Kino AI </title>

<div id="img_logo">
  <a href="{% url 'kino_app:index' %}" > <img id="logo" width="480" height="480" src="{% static 'kino_app/logo/logo_cut.png' %}" ></a>

</div>

{% if msg %}
  <div id="msg"> {{msg}} </div>
{% endif %}


<form action="{% url 'kino_app:upload' %}" method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  {% if title %}
    <h3> Upload a video into the project {{title|replace_underscore}}</h3>
    <input type="hidden" name="title" value="{{title}}"/>
    <input type="checkbox" id='private' name="private"
         >
     <label for='private'> Private </label>
  {% endif %}
  <input type="file" name="fileToUpload" id="fileToUpload">
  <input type="submit" value="Upload Video" name="submit" onClick="clickSub()">
</form>

<div id='wait'></div>
<script>
var div = document.getElementById("wait");
</script>

<script>
function clickSub() {
  var para = document.createElement("p");
  var node = document.createTextNode("Your video is processing...");
  para.appendChild(node);
  div.appendChild(para);
}
</script>

kino_app/templates/kino_app/video_editing.html
<!--
This file is part of KinoAi project.
It is subject to the license terms in the LICENSE file found in the top-level directory
-->

{% load static %}
{% load string_filter %}

<html>
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'kino_app/kino_ai/stylesheets/table.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'kino_app/kino_ai/stylesheets/index_style.css' %}">

    <script src="{% static 'kino_app/jquery.min.js' %}"></script>
    <script src="{% static 'kino_app/dash.all.min.js' %}"></script>
    <script src="{% static 'kino_app/p5.min.js' %}"></script>
    <!-- <script src="{% static 'kino_app/opencv.js' %}"></script> -->
    <script src="{% static 'kino_app/addons/p5.dom.min.js' %}"></script>
    <script src="{% static 'kino_app/addons/p5.sound.min.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/preparation_editor.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/cadrage_editor.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/split_screen_editor.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/montage_editor.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/annotation_editor.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/export_editor.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/actor_timeline.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/tracklet.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/erase_button.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/go_button.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/state_button.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/player.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/shots_timeline.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/shot.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/track_bbox_shot.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/bbox_shot.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/annotation_timeline.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/actor_annotation.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/note_editor.js' %}"></script>
    <script src="{% static 'kino_app/kino_ai/partition.js' %}"></script>
    <title> Kino AI </title>

    <script>
        // var json_detec = "{% static 'kino_app/data/' %}{{path}}/detections.json";
        // var json_detec_test = "{{data_detec}}";
        // var data_detects = JSON.parse(json_detec_test.replace(/&quot;/g,'"'));
        var username = "{{username}}";
        var json_data_note = JSON.parse("{{data_note}}".replace(/&quot;/g,'"').replace(/&amp;/g,"&").replace(/&#x27;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">"));
        var user_timeline = JSON.parse("{{user_timeline}}".replace(/&#x27;/g,'"').replace(/&#39;/g,'"'));
        var user_partitions = JSON.parse("{{user_partitions}}".replace(/&#x27;/g,'"').replace(/&#39;/g,'"'));
        let b;
        for(let u of user_partitions){if(u==username){b=true;break;}}
        if(user_partitions.length==0 || !b) {user_partitions.push(username);}
        var sub_granted = true;
        // if("{{owner}}"=="None") {
        //   sub_granted = false;
        // }
        var data_path_video_export = JSON.parse("{{data_path_video_export}}".replace(/&quot;/g,'"'));
        var data_partitions;
        var owner = "{{owner}}";
        var abs_path = "{{abs_path}}";
        var original_width = "{{width}}";
        var original_height = "{{height}}";
        var original_frame_rate = "{{frame_rate}}";
        var id_db = "{{id}}";
        // console.log(original_width, original_height, original_frame_rate);
    </script>
    <script src="{% static 'kino_app/kino_ai/main.js' %}"></script>


    <title>KinoAI</title>
   </head>

   <body>
     <div id='header_info' class="">
     <div class="">
     <a class="" href="{% url 'kino_app:index' %}" ><img class="" id="logo" width="140" height="140" src="{% static 'kino_app/logo/logo_cut.png' %}" ></a>
     </div>
     <div class="" id='user_info'>
       <h2>{{part}}</h2>
       {% if prev_id %}
          <a class="" href="{% url 'kino_app:video_editing' prev_id%}" ><img class=" arrow" width="70" height="35" src="{% static 'kino_app/logo/prev.png' %}" ></a>
        {% endif %}
       {% if next_id %}
          <a class="" href="{% url 'kino_app:video_editing' next_id%}" ><img class=" arrow" width="70" height="35" src="{% static 'kino_app/logo/next.png' %}" ></a>
        {% endif %}
       <form action="{% url 'kino_app:upload_rough' %}" method="post" id='rough'>
               {% csrf_token %}
               <input type="file" name="fileToUpload" id="fileToUpload"/>
               <input type="hidden" id="abs_path" name="abs_path" value="{{abs_path}}">
               <input type="submit" value="Upload" class='user_button'/>
           </form>
     </div>
      <h1 id="video_title" class="">{{title|replace_underscore}}</h1>
    </div>
     <div id="div_player">
         <video id="videoPlayer" controls></video>
         <script>
              (function(){
                  var url = "/media/kino_app/data/{{path}}/mpd/original_dash.mpd";
                  dash_player = dashjs.MediaPlayer().create();
                  dash_player.initialize(document.querySelector("#videoPlayer"), url, false);
              })();
          </script>
     </div>

     <div id='opencv_out' ></div>
     {% block javascript %}
     <script>
     let off = document.getElementById('user_info').offsetHeight - document.getElementById("div_player").offsetTop+10;
     if((document.getElementById('logo').offsetHeight - document.getElementById("div_player").offsetTop)>off) {
       off = document.getElementById('logo').offsetHeight - document.getElementById("div_player").offsetTop +30;
     }
     document.getElementById('header_info').style.padding =  " 0 0 "+off.toString()+" 0";

     // document.getElementById('logo').onclick = saveTimeline;

     // Attach a submit handler to the form
     function upload(event) {
        event.preventDefault();
        var data = new FormData($('#rough').get(0));

        $.ajax({
           url: $(this).attr('action'),
           type: $(this).attr('method'),
           data: data,
           cache: false,
           processData: false,
           contentType: false,
           success: function(data) {
              let type = data['type'];
              if(type == 'json') {
                let value = JSON.parse(data['data'].replace(/&quot;/g,'"'));
                if(value) {
                  rough_json = value;
                  if(rough_json) {
                    if(exploit_rough) {
                      exploit_rough.remove();
                    }
                    exploit_rough = createButton('Roughisation');
                    html_elements.push(exploit_rough);
                    exploit_rough.side = true;
                    exploit_rough.mousePressed(exploitRoughCut);
                    positionUIElements();
                  }
                }
              } else if(type == 'vtt') {
                $('#div_sub').remove();
                div_sub = undefined;
                let i=0;
                for(let t of video.elt.textTracks) {
                  if(i>0) {
                    t.mode = 'disabled';
                  }
                  i++;
                }
                if(montage_editor) {
                  montage_editor.show_sub.checked(true);
                  montage_editor.is_show_sub = true;
                  if(is_montage_editor) {
                    montage_editor.show_sub.show();
                    console.log(data);
                  }
                }
                setSubtitle(data);
              }
           }
        });
        return false;
      }

      $(function() {
         $('#rough').submit(upload);
      });

      $('body').on('focus', '[contenteditable]', function() {
          const $this = $(this);
          $this.data('before', $this.html());
      }).on('blur keyup paste input', '[contenteditable]', function() {
          const $this = $(this);
          if ($this.data('before') !== $this.html()) {
              $this.data('before', $this.html());
              $this.trigger('change');
              for(let act of preparation_editor.actors_timeline) {
                if($(this).is(act.elem.elt)) {
                  act.setActorName($(this)[0].innerText);
                }
              }
              if($(this).is(shots_timeline.name_elem.elt)) {
                shots_timeline.changeName($(this)[0].innerText);
              }
          }
      });

      $(document).bind('keydown', function(e) {
        if((e.ctrlKey || e.metaKey) && (e.which == 83)) {
          e.preventDefault();
          if(sub_granted) {
            saveTimeline();
          } else {
            console.log("not allowed");
          }

          key_down = undefined;
          return false;
        }
      });

      // window.onload = function() {let zoom = (windowHeight/12)/$('#header_info').height();$('#header_info').css('zoom',zoom);};
     </script>
     {% endblock %}

     <!-- <footer id='footer'>
       Rémi Colin de Verdière - Imagine - Inria
     </footer> -->
  </body>
</html>

kino_app/templates/kino_app/videos_library.html
<!--
This file is part of KinoAi project.
It is subject to the license terms in the LICENSE file found in the top-level directory
-->


{% load static %}
{% load string_filter %}
<link rel="stylesheet" type="text/css" href="{% static 'kino_app/kino_ai/stylesheets/index_style.css' %}">
<script src="{% static 'kino_app/jquery.min.js' %}"></script>
<style type="text/css">
#curr_video, #curr_audio {
  width: 40%;
  margin: 10;
}
#top_info {
  margin-bottom: 100;
  margin: 10;
  padding: 10;
  border: 2px solid #2E5C9C;
  background-color: white;
}
#videos_list, #audios_list {
  overflow: auto;
}
#videos_list li, #audios_list li{
  width: auto;
  border: none;
  margin-left: 10;
  font-size: 20;
}

button, input {
  padding: 5;
  background-color: #2E5C9C;
  color: white;
  cursor : pointer;
  text-decoration: none;
  border: none;
}
input::placeholder {
  color: white;
}
</style>
<title> Kino AI </title>

<div id='header_info'>

<div class="aside">
  <a class="aside" href="{% url 'kino_app:index' %}" ><img class="aside" id="logo" width="140" height="140" src="{% static 'kino_app/logo/logo_cut.png' %}" ></a>
</div>
<h1>Videos library</h1>
</div>

<div id="top_info">

  <form id="check_password_library" action="{% url 'kino_app:check_password_library' %}" method="post" >
      {% csrf_token %}
      <h3>Password</h3>
      <input placeholder="password" type="password" name="password" />
      <input type="hidden" name="project" value="{{project}}"/>
      <input type="submit" value="Submit"/>
  </form>

  <form action="{% url 'kino_app:upload_video_library' %}" method="post" enctype="multipart/form-data" id="upload">
    {% csrf_token %}
    <h3> {{project|replace_underscore}}</h3>
    <input type="hidden" name="project" value="{{project}}"/>
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Video" name="submit" onClick="clickSub()">
  </form>

  <script>var videos = []; var audios = [];</script>
  <ul id="videos_list">
  <h3>Videos</h3>
    {% for v in videos %}
      <script> videos.push({'Name':"{{v.Name}}", 'src':"{{v.src}}"}); </script>
      <li><button onclick="clickVideo(this)" class="" id="{{v.src}}">{{v.Name|replace_underscore}}</button></li>
    {% endfor %}
  </ul>
  <ul id="audios_list">
  <h3>Audios</h3>
    {% for a in audios %}
      <script> audios.push({'Name':"{{a.Name}}", 'src':"{{a.src}}"}); </script>
      <li><button onclick="clickAudio(this)" class="" id="{{a.src}}">{{a.Name|replace_underscore}}</button></li>
    {% endfor %}
  </ul>
</div>

<video controls id="curr_video"></video>
<audio controls id="curr_audio"></audio>
<script>
var active_library = "{{ request.session.active_library }}";
var project = "{{project}}";

let off = document.getElementById('logo').offsetHeight - document.getElementById("top_info").offsetTop+15;
document.getElementById('header_info').style.padding =  " 0 0 "+off.toString()+" 0";

if(active_library == "true") {
  document.getElementById('check_password_library').style.display = "none";
} else {
  document.getElementById('upload').style.display = "none";
  document.getElementById('videos_list').style.display = "none";
  document.getElementById('audios_list').style.display = "none";
}
document.getElementById('curr_video').style.display = "none";
document.getElementById('curr_audio').style.display = "none";
$.post({
  url: window.location.origin+"/kino_app/set_library_false",
  async: true,
  data: {'name': ''},
  dataType: 'json',
  success: function (data) {
    // console.log(data);
  }
});

function clickSub() {
  var para = document.createElement("p");
  para.innerText = "Your video is processing...";
  document.body.appendChild(para);
}

function clickVideo(el) {
  document.getElementById('curr_audio').style.display = "none";
  document.getElementById('curr_audio').pause();
  let vid = document.getElementById('curr_video');
  while(vid.firstChild){vid.firstChild.remove();}
  vid.style.display = "block";
  var sourceMP4 = document.createElement("source");
  sourceMP4.type = "video/mp4";
  sourceMP4.src = el.id;
  vid.appendChild(sourceMP4);
  vid.currentTime =0;
  vid.load();
  vid.play();
  window.scroll(0,vid.offsetTop);
}

function clickAudio(el) {
  document.getElementById('curr_video').style.display = "none";
  document.getElementById('curr_video').pause();
  let audio = document.getElementById('curr_audio');
  while(audio.firstChild){audio.firstChild.remove();}
  audio.style.display = "block";
  var source = document.createElement("source");
  source.type = "audio/ogg";
  source.src = el.id;
  audio.appendChild(source);
  audio.currentTime =0;
  audio.load();
  audio.play();
  window.scroll(0,audio.offsetTop);
}

function removeVideo(video) {
  console.log(video);
  $.post({
    url: window.location.origin+"/kino_app/remove_video_library",
    async: true,
    data: {'path': video.src.split('media')[1], 'project':project},
    dataType: 'json',
    success: function (data) {
      // console.log(data);
    }
  });
}

</script>